### ISSUE TITLE
FritzBox Anmeldung 

### ISSUE THREAD

**Issue by longgiangp** [Blackbox-git/HousekeepingPi#1]
Ausgangslage:

- FB 7590 mit der FritzOS Version 7.21
- RPI 2 B+ mit Raspberry Pi OS Lite 5.4.72-v7+
- 1x AVM DECT 200 an Siemens Waschmaschine (Drehrad und Touchbuttons) im Waschkeller

Folgende Einstellungen musste ich vornehmen, damit eine Verbindung überhaupt zustande kommt (sonst Fehler laut Syslog: Passwort falsch):

1) System -> FritzBox Benutzer -> Reiter: Benutzer -> Button: Benutzer hinzufügen -> Abschnitt: Berechtigungen: Auswählen: FritzBox Einstellung (**!**), Sprachnachichten etc. (**!**), Smart-Home (logisch)

Anscheinend meldet sich das Programm PyDect200 laut der Syslog über die Benutzeroberfläche an, wofür die Berechtigungen zu den FritzBox Einstellungen benötigt werden. Das finde ich etwas bedenklich und abwegig. So hat mich die Fehlersuche Stunden gekostet, weil ich mich eher an Ihrem Artikel gehalten habe und gar nicht daran gedacht habe. 

2) System -> FritzBox Benutzer -> Reiter: Anmeldung im Heimnetz -> Auswahl: Anmeldung mit FRITZ!Box-Benutzernamen und Kennwort

Ich habe ebenfalls gerätselt warum die Meldungen im Programm aufzeichnung.py zu der Funktion verbindung() auskommentiert waren. Das wäre schließlich hilfreich gewesen.
Zum Testen musste ich mir ebenfalls PyDect200_Demo.py von mperlet ziehen.

Aktuell bereitet mir nur das Thema unter Punkt 1 etwas Bauchschmerzen. Evtl muss das PyDect200 Programm am aktuellen FritzOS ausgiebig getestet werden. 

Ansonsten finde ich Ihre Lösung sehr schön und ich bedanke mich für das Zusammenstellen. Besonders hilfreich ist das Projekt bei Wohnungen mit Waschküchen im Keller.

**Comment by MarRich1** [comment]
Hatte auch Probleme mit der Anmeldung, das lag aber daran, dass der "Default" Login noch aktiv war, also der Login der nur mit Passwort geht. 
Unter System > Fritzbox-Benutzer die Einstellung auf "Anmeldung mit FRITZ!Box-Benutzernamen und Kennwort" ändern hat bei mir geholfen

Dann hat es auch mit "Smart-Home" Rechten alleine geklappt
